fapflix/fapflix/urls.py
from django.contrib import admin
from django.contrib.staticfiles import views
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import debug_toolbar

urlpatterns = [
    path("", include(("viewer.urls", "viewer"), namespace="viewer")),
    path("admin/", admin.site.urls),
    path("__debug__/", include(debug_toolbar.urls)),
]
if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    # urlpatterns += [
    #     re_path(r"^static/(?P<path>.*)$", views.serve),
    # ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fapflix/viewer/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("actor_edit/<int:pk>/", views.EditActorView.as_view(), name="edit-actor"),
    path(
        "actor_delete/<int:pk>/", views.DeleteActorView.as_view(), name="delete-actor"
    ),
    path("actor/<int:pk>/", views.ActorView.as_view(), name="actor"),
    path("update-actor/", views.updateActor, name="actor-add-content"),
    path("removeActorVideo/", views.actor_remove_video, name="actor-video-delete"),
    path("removeActorImage/", views.actor_remove_image, name="actor-image-delete"),
    path("actors/", views.ActorsView.as_view(), name="actors"),
    path("addVideoLabel/", views.add_video_label, name="label-video-add"),
    path("changeAge/", views.change_age, name="change-age"),
    path("deleteActorLabel/", views.delete_actor_label, name="label-actor-delete"),
    path("deleteVideoLabel/", views.delete_video_label, name="label-video-delete"),
    path("fav/<int:videoid>/", views.add_favorite, name="add_favorites"),
    path(
        "fav_image/<int:imageid>/", views.add_favorite_image, name="add_favorite_image"
    ),
    path("generate_actor/", views.CreateActorView.as_view(), name="generate-actor"),
    path("label/<int:pk>/", views.LabelResultView.as_view(), name="label-result-view"),
    path("label/<int:pk>/delete/", views.delete_label, name="label-delete"),
    path("labels/", views.LabelView.as_view(), name="labels"),
    path("load/", views.DataLoader.as_view(), name="load"),
    path("loadData/", views.load_data, name="load-data"),
    path("cleanData/", views.clean_data, name="clean-data"),
    path("loadPostVideo/", views.post_process_video_controller, name="load-post-video"),
    path("loadPostImage/", views.post_process_image_controller, name="load-post-image"),
    path("new_actor/", views.add_actor, name="new-actor"),
    path("rateVideo/", views.rate_video, name="rate-video"),
    path("remfav/<int:videoid>/", views.rem_favorite, name="rem_favorites"),
    path(
        "remfav_image/<int:imageid>/",
        views.rem_favorite_image,
        name="rem_favorite_image",
    ),
    path("remvid/", views.rem_video, name="rem_video"),
    path("remimage/", views.rem_image, name="rem-image"),
    path("search/", views.SearchView.as_view(), name="search"),
    path("video/<int:pk>/", views.VideoView.as_view(), name="video"),
    path("videoOverview/", views.VideoOverview.as_view(), name="video-overview"),
    path("imageOverview/", views.ImageOverview.as_view(), name="image-overview"),
]

fapflix/viewer/models.py
from django.db import models
from datetime import datetime
from pathlib import Path
import django
from numpy.core.numeric import full


class Labels(models.Model):
    label = models.TextField(unique=True)

    class Meta:
        ordering = ["label"]

    def __unicode__(self):
        return f"{self.label}"

    def __str__(self):
        return f"{self.label}"


class Videos(models.Model):
    path = models.TextField(unique=True)
    filename = models.TextField()
    dim_height = models.IntegerField(null=True)
    dim_width = models.IntegerField(null=True)
    duration = models.FloatField()
    audiocodec = models.TextField(null=True)
    bitrate = models.BigIntegerField(null=True)
    size = models.BigIntegerField()
    videocodec = models.TextField(null=True)
    preview = models.TextField()
    thumbnail = models.TextField()
    processed = models.BooleanField()
    rating = models.FloatField(default=0)
    favorite = models.BooleanField(default=False)
    labels = models.ManyToManyField(Labels)
    inserted_at = models.DateTimeField(default=django.utils.timezone.now)
    actor_age = models.IntegerField(null=True)

    def __str__(self):
        return f"{self.filename}"

    def _delete_faces(self):
        path = Path("/srv/data/fapflix/media/images/faces")
        faces = path.glob(f"{self.id}_*.jpg")
        for face in faces:
            face.unlink()
            print(f"Deleted face: {face}")
        full_face = path.parent / "full_faces" / f"{self.id}_face.jpg"
        if full_face.is_file():
            full_face.unlink()

    def _delete_previews(self):
        path = Path("/srv/data/fapflix/viewer/static/viewer/images")
        previews = path / "previews/"
        thumbnails = path / "thumbnails/"
        preview = previews / f"{self.id}.jpg"
        if preview.is_file():
            preview.unlink()
        print(f"deleted {preview}")
        thumbnail = thumbnails / f"{self.id}.jpg"
        if thumbnail.is_file():
            thumbnail.unlink()
        print(f"deleted {thumbnail}")

    def delete_full(self):
        obj = Path(self.path)
        print(f"Deleting {self.id}...")
        try:
            obj.unlink()
        except (PermissionError, FileNotFoundError) as e:
            print("Couldn't delete, file busy or already deleted.")
        self._delete_faces()
        self._delete_previews()
        self.delete()

    def file_exists(self):
        obj = Path(self.path)
        if obj.is_file():
            return True
        else:
            return False

    def clean(self):
        if not self.file_exists():
            self.delete()
            return 1
        return 0

    class Meta:
        ordering = ["?"]
        indexes = [
            models.Index(fields=["path"]),
        ]


class Images(models.Model):
    path = models.TextField(unique=True)
    filename = models.TextField()
    dim_height = models.IntegerField(null=True)
    dim_width = models.IntegerField(null=True)
    size = models.IntegerField()
    processed = models.BooleanField(default=False)
    favorite = models.BooleanField(default=False)
    inserted_at = models.DateField(default=django.utils.timezone.now)
    labels = models.ManyToManyField(Labels)
    actor_age = models.IntegerField(null=True)

    def _delete_faces(self):
        path = Path("/srv/data/fapflix/media/images/faces")
        faces = path.glob(f"image_{self.id}.jpg")
        for face in faces:
            face.unlink()
            print(f"Deleted face: {face}")
        full_face = path.parent / "full_faces" / f"image_{self.id}_face.jpg"
        if full_face.is_file():
            full_face.unlink()

    def delete_full(self):
        obj = Path(self.path)
        print(f"Deleting {self.id}...")
        try:
            obj.unlink()
        except (PermissionError, FileNotFoundError) as e:
            print("Couldn't delete, file busy or already deleted.")
        self._delete_faces()
        self.delete()

    def clean(self):
        if not self.file_exists():
            self.delete()
            return 1
        return 0

    def file_exists(self):
        obj = Path(self.path)
        if obj.is_file():
            return True
        else:
            return False

    def __str__(self):
        return f"{self.filename}"

    class Meta:
        ordering = ["-inserted_at"]
        indexes = [
            models.Index(fields=["path"]),
        ]


class Actors(models.Model):
    forename = models.TextField(null=True)
    surname = models.TextField(null=True)
    birth_year = models.IntegerField(null=True)
    nationality = models.TextField(null=True)
    labels = models.ManyToManyField(Labels, blank=True)
    videos = models.ManyToManyField(Videos, blank=True)
    images = models.ManyToManyField(Images, blank=True)
    avatar = models.ImageField(
        upload_to="images/actor_profiles/", null=True, blank=True
    )

    def age(self):
        today = datetime.now().date()
        if self.birth_year:
            return today.year - self.birth_year
        else:
            return

    def _delete_actor_profile(self):
        media_path = Path("/srv/data/fapflix/media/")
        profile_path = media_path / str(self.avatar)
        print(profile_path)
        try:
            profile_path.unlink()
        except (PermissionError, FileNotFoundError) as e:
            print("Couldn't delete, file busy or already deleted.")

    def delete_full(self):
        print(f"Deleting {self.id}...")
        self._delete_actor_profile()
        self.delete()

    def __str__(self):
        return f"{self.forename} - {self.surname} - {self.birth_year}"

fapflix/viewer/forms.py
from django import forms
from .models import Actors, Videos
from django.views.generic.edit import UpdateView


class FilterForm(forms.Form):
    FILTERS = [
        ("rating", "rating"),
        ("favorite", "favorites"),
        ("dim_width", "resolution"),
        ("inserted_at", "newest"),
        ("duration", "longest"),
    ]
    filter_videos = forms.ChoiceField(choices=FILTERS)


class LabelForm(forms.Form):
    label = forms.CharField(label="Label", max_length=100)


class ImageForm(forms.ModelForm):
    """Form for the image model"""

    class Meta:
        model = Actors
        fields = ("avatar",)


class DeleteActorForm(forms.ModelForm):
    class Meta:
        model = Actors
        fields = ("id",)


class OrderedModelMultipleChoiceField(forms.ModelMultipleChoiceField):
    def clean(self, value):
        qs = super(OrderedModelMultipleChoiceField, self).clean(value)
        return qs


class ActorForm(forms.ModelForm):
    """Form for the image model"""

    videos = OrderedModelMultipleChoiceField(Videos.objects.order_by("filename"))

    class Meta:
        model = Actors
        fields = (
            "forename",
            "surname",
            "birth_year",
            "nationality",
            "labels",
            "videos",
            "images",
            "avatar",
        )

fapflix/viewer/templates/viewer/actor.html
{% extends 'viewer/base.html' %}
{% load static %}
{% load custom_filters %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h2 class="info-field">{{object.forename}} {{object.surname}}</h2>
        </div>
        <div class="col-lg-12 row actor-media-box">
            <div class="col-lg-3">
                {% if object.avatar %}
                <img class="actor-profile-img" src="/viewer/images/{{ object.avatar }}"
                    alt="{{object.forename}}{{object.surname}}">
                {% else %}
                <img class="actor-profile-img" src="{% static 'viewer/images/actor_profiles/thumbnail.png' %}"
                    alt="{{object.forename}}{{object.surname}}">
                {% endif %}
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Upload</button>
                </form>
            </div>
            <div class="col-lg-3">
                <table>
                    <tr>
                        <th>Born in: </th>
                        <td>{{object.birth_year}}</td>
                    </tr>
                    <tr>
                        <th>Age:</th>
                        <td>{{object.age}}</td>
                    </tr>
                    <tr>
                        <th>Nationality:</th>
                        <td>{{object.nationality}}</td>
                    </tr>
                    <tr>
                        <th>Videos:</th>
                        <td>{{object.videos.all|length}}</td>
                    </tr>
                    <tr>
                        <th>Images:</th>
                        <td>{{object.images.all|length}}</td>
                    </tr>
                    <tr>
                        <th>Labels:</th>
                        <td> {% for label in object.labels.all %}
                            <small class="card-text video-label">
                                <a href="/label/{{label.id}}/">{{label.label}}</a><a onclick="remActorLabel(this)"
                                    class="delete-icon" label-id="{{label.id}}" actor-id="{{object.id}}"><i
                                        class="fas fa-trash-alt"></i></a>
                            </small>

                            {% endfor %}
                        </td>
                    </tr>
                </table>



            </div>
            <div class="col-lg-3 ">

                {% if best_rated %}
                <h3>Best rated video:</h3>
                <div id='carouselSW-content-{{id}}' class="imgSW-preview actor-video float-right">
                    <a href="{% url 'viewer:video' best_rated.id %}">
                        <img src="{% static 'viewer/images/thumbnails/' %}{{best_rated.thumbnail}}"
                            preview="{% static 'viewer/images/previews/' %}{{best_rated.preview}}"
                            class="car-preview-img video-preview" name='preview-{{best_rated.id}}'
                            alt="{{best_rated.filename}}">
                    </a>
                    <div class="img-overlay">
                        <p>{{best_rated.filename|truncatechars:35}}</p>
                    </div>
                </div>
                {% endif %}


            </div>
            <div class="col-lg-12"></div>
        </div>
        <div class="col-lg-1 offset-lg-9">
            <a class="btn btn-primary my-2 my-sm-0 float-right" onclick="addContent(this)">Load related content</a>
        </div>
        <div class="col-lg-1">
            <a class="btn btn-primary my-2 my-sm-0 float-right" href="{% url 'viewer:edit-actor' object.id %}">Edit</a>
        </div>
        <div class="col-lg-1">
            <form action="{% url 'viewer:delete-actor' object.id %}" method="post">
                {{delete_form.id}}
                <button class="btn btn-primary my-2 my-sm-0 float-right" type="submit">Delete</button>
            </form>
        </div>
        <div class="col-lg-12">
            <p id="load-icon" style="display:none"><i class="fas fa-spinner fa-spin"></i> Running face recognition.
                Depening on your library size, this might take a while</p>
        </div>
        <div class="col-lg-12 actor-carousel">
            <h3>Videos ({{object.videos.all|length}}):</h3>
            {% if object.videos.all %}
            <div class="row">
                {% for video in object.videos.all %}
                <div class="col-lg-3 col-md-4 col-12 img_preview img_side" id="{{video.id}}">
                    <a href="{% url 'viewer:video' video.id %}">
                        <img src="{% static 'viewer/images/thumbnails/' %}{{video.thumbnail}}"
                            preview="{% static 'viewer/images/previews/' %}{{video.preview}}"
                            thumbnail="{% static 'viewer/images/thumbnails/' %}{{video.thumbnail}}"
                            class="car-preview-img video-preview" dataframes="100" name='preview-{{video.id}}'
                            alt="{{video.filename}}" style="width:100%;">
                    </a>
                    <div class="video-delete">
                        <a onclick=removeVideo(this) video-id="{{video.id}}" actor-id="{{object.id}}">
                            Remove <i class="fas fa-trash-alt"></i></a>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% endif %}
            <h3>Images ({{object.images.all|length}}):</h3>
            {% if object.images.all %}
            <div class="row">
                {% for image in object.images.all %}
                <div class="col-lg-3 image-overview-card">
                    <a href="{% static 'viewer/ext_videos/' %}{{image.filename|urlencode}}">
                        <img src="{% static 'viewer/ext_videos/' %}{{image.filename|urlencode}}" id="{{image.id}}"
                            class="image-preview" alt="{{image.filename}}">
                    </a>
                    <div class="image-delete">
                        <a onclick=removeImage(this) image-id="{{image.id}}" actor-id="{{object.id}}">
                            Remove <i class="fas fa-trash-alt"></i></a>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% endif %}

            <!-- {% for face in faces %}
            <img src="/viewer/images/images/full_faces/{{face}}" class="image-preview">
            {% endfor %} -->

        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script type="text/javascript">
    function removeVideo(button) {
        $(button).parent().hide();
        $("#" + $(button).attr("video-id")).hide();
        $.ajax({
            url: "{% url 'viewer:actor-video-delete' %}",
            method: "POST",
            data: {
                video_id: $(button).attr("video-id"),
                actor_id: $(button).attr("actor-id")
            }
        })
    };
    function removeImage(button) {
        $(button).parent().hide();
        $("#" + $(button).attr("image-id")).hide();
        $.ajax({
            url: "{% url 'viewer:actor-image-delete' %}",
            method: "POST",
            data: {
                image_id: $(button).attr("image-id"),
                actor_id: $(button).attr("actor-id")
            }
        })
    };
    function addContent(button) {
        $("#load-icon").show();
        $.ajax({
            url: "{% url 'viewer:actor-add-content' %}",
            method: "POST",
            data: {
                actor: "{{object.id}}"
            }, success: function (data) {
                id = data["actor-id"];
                window.location = "/actor/" + id + "/"
            }
        })
    };
    function remActorLabel(button) {
        $(button).parent().hide();
        $.ajax({
            url: "{% url 'viewer:label-actor-delete' %}",
            method: "POST",
            data: {
                label_id: $(button).attr("label-id"),
                actor_id: "{{object.id}}"
            }
        })
    }</script>
{% endblock %}

fapflix/viewer/templates/viewer/actors.html
{% extends 'viewer/base.html' %}
{% load custom_filters %}
{% block content %}
<div class="container">
    <a class="btn btn-danger" href="{% url 'viewer:new-actor' %}">add new actor</a>
    <div class="card-deck">
        {% for actor in object_list %}
        {% include "viewer/actor_card.html" with actor=actor %}
        {% endfor %}
    </div>
</div>


{% endblock %}


{% block script %}
<script type="text/javascript">
    function remActorLabel(button) {
        $(button).parent().hide();
        $.ajax({
            url: "{% url 'viewer:label-actor-delete' %}",
            method: "POST",
            data: {
                label_id: $(button).attr("label-id"),
                actor_id: $(button).attr("actor-id"),
            }
        })
    }</script>
{% endblock %}

fapflix/viewer/templates/viewer/video.html
{% extends 'viewer/base.html' %}
{% load humanize %}
{% load static %}
{% load custom_filters %}
{% block content %}
<link href="https://vjs.zencdn.net/7.11.4/video-js.css" rel="stylesheet" />
<div class="container-fluid">
    <div class="row">
        <div class='col-lg-8 col-md-12 video-block'>
            <h1>{{video.filename}}</h1>
            <div class="embed-responsive embed-responsive-16by9 video">
                <video id="vid-{{video.id}}" class="video-js embed-responsive-item" controls="" preload="auto"
                    poster="{% static 'viewer/images/thumbnails/' %}{{video.thumbnail}}" loop="true">
                    <source src="{% static 'viewer/ext_videos' %}{{video.filename|urlencode}}" type="{{video.filename|get_type}}">
                    <p class="vjs-no-js">
                        To view this video please enable JavaScript, and consider upgrading to a
                        web browser that
                        <a href="https://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
                    </p>
                </video>
            </div>
            <div class="row justify-content-between" style="min-height:50px">
                <div class="col-lg-10 no-padding-left">
                    <div class="row  video-labels">
                        {% for v_label in video.labels.all %}
                        <div class="video-label col-lg-2 col-sm-6">
                            <a href="/label/{{v_label.id}}/">{{v_label.label}}</a><a onclick="remVideoLabel(this)"
                                class="delete-icon" label-id="{{v_label.id}}"><i class="fas fa-trash-alt"></i></a>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="col-lg-2 col-sm-12 no-padding-left">
                    <select class="label-select float-right" list="add-label" id="label-choice" name="label-choice" />
                    <option value="" disabled selected>Add Label</option>
                    {% for label in labels %}
                    <option value="{{label.id}}">{{label.label}}</option>
                    {% endfor %}
                    </select>
                </div>
            </div>
            <div class="row justify-content-between video-infos">
                <div class="col-lg-2 no-padding-left">
                    <a class='btn btn-danger video-info-obj' id='rem-vid' onclick=remvid(this) href="#">
                        <span>Delete File</span> <i class="fas fa-trash"></i></i></a>
                </div>
                <div class="col-lg-1 form__group field" style="margin-top:0;">
                    <label for="age" class="form__label">Age</label>
                    <input id="video-info-age" class="video-filter-obj form__field" type="number" size="6" name="age"
                        max="99" value="{{video.actor_age}}">
                </div>
                <div class="col-lg-2 form__group field" style="margin-top:0;">
                    <label class="form__label">Actors</label>

                    {% for actor in video.actors_set.all %}
                    <a href="{% url 'viewer:actor' actor.id %}">{{actor.forename}} {{actor.surename}}</a>
                    {% endfor %}

                </div>
                <div class="col-lg-2 no-padding-left" style="margin-top:0;">
                    {% if video.processed %}
                    <a class='btn btn-danger video-info-obj' onclick="generateActor(this)">Generate actor</a>
                    {% endif %}
                </div>
                <div class="col-lg-4">
                    <fieldset class="rating">
                        <input type="radio" id="star5" name="rating" value="5" /><label for="star5"
                            title="Hot!"></label>
                        <input type="radio" id="star4" name="rating" value="4" /><label for="star4"
                            title="Pretty good"></label>
                        <input type="radio" id="star3" name="rating" value="3" /><label for="star3" title="Meh"></label>
                        <input type="radio" id="star2" name="rating" value="2" /><label for="star2"
                            title="Kinda bad"></label>
                        <input type="radio" id="star1" name="rating" value="1" /><label for="star1"
                            title="Sucks big time"></label>
                    </fieldset>
                </div>
                <div class="col-lg-1">
                    {% if video.favorite %}
                    <a class='float-left video-info-obj' id='rem-fav' onclick=remfav(this)><i
                            class="fas fa-heart"></i></a>
                    {% else %}
                    <a class='float-left video-info-obj' id='add-fav' onclick=addfav(this)><i
                            class="far fa-heart"></i></a>
                    {% endif %}
                </div>
                <div class="col-lg-12">
                    <p id="load-icon" style="display:none"><i class="fas fa-spinner fa-spin"></i> Running face
                        recognition. Depening on your library size, this might take a while</p>
                </div>
            </div>

        </div>
        {% if recommendations|length > 1 %}
        <div class='col-lg-4 col-md-12'>
            <h3 style='font-size:2rem'>Recommendations:</h3>
            <div class='border'>
                <div class="row">
                    {% for video in recommendations|slice:":8" %}
                    <div class="col-lg-6 col-md-4 col-12 img_preview img_side">
                        <a href="{% url 'viewer:video' video.id %}">
                            <img src="{% static 'viewer/images/thumbnails/' %}{{video.thumbnail}}"
                                preview="{% static 'viewer/images/previews/' %}{{video.preview}}"
                                thumbnail="{% static 'viewer/images/thumbnails/' %}{{video.thumbnail}}"
                                class="car-preview-img video-preview" dataframes="100" name='preview-{{video.id}}'
                                alt="{{video.filename}}" style="width:100%;">
                        </a>
                        <div class="img-overlay">
                            <p>{{video.filename|truncatechars:35}}</p>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        {% if recommendations|length >= 14 %}
        <div>
            {% include "viewer/carousel.html" with id="carousel1"  title="Further recommendations:" result_set=recommendations|slice:"8:32" type="videos" %}
        </div>
        {% endif %}
        {% else %}
        <div class='col-lg-4 col-md-12'>
            <h3 style='font-size:2rem'>Other videos:</h3>
            <div class='border'>
                <div class="row">
                    {% for video in rvideos|slice:":8" %}
                    <div class="col-lg-6 col-md-4 col-12 img_preview img_side">
                        <a href="{% url 'viewer:video' video.id %}">
                            <img src="{% static 'viewer/images/thumbnails/' %}{{video.thumbnail}}"
                                preview="{% static 'viewer/images/previews/' %}{{video.preview}}"
                                thumbnail="{% static 'viewer/images/thumbnails/' %}{{video.thumbnail}}"
                                class="car-preview-img video-preview" dataframes="100" name='preview-{{video.id}}'
                                alt="{{video.filename}}" style="width:100%;">
                        </a>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        {% if rvideos|length >= 14 %}
        <div>
            {% include "viewer/carousel.html" with id="carousel1" title="Further recommendations:" result_set=rvideos|slice:"8:32" type="videos" %}
        </div>
        {% endif %}


        {% endif %}
    </div>
</div>
{% endblock %}

{% block script %}
<script src="https://vjs.zencdn.net/7.11.4/video.min.js"></script>
<script type="text/javascript">
    function addfav(button) {
        const Http = new XMLHttpRequest();
        const url = "{% url 'viewer:add_favorites' video.id %}"
        Http.open("GET", url);
        Http.send();
        button.setAttribute("onClick", "remfav(this)");
        button.setAttribute("id", "rem-fav");
        $(button).children()[0].setAttribute("class", "fas fa-heart");
    }
    function generateActor(button) {
        $("#load-icon").show();
        $.ajax({
            url: "{% url 'viewer:generate-actor' %}",
            method: "POST",
            data: {
                videos: ["{{video.id}}"]
            }, success: function (data) {
                id = data["actor-id"];
                window.location = "/actor/" + id + "/"
            }, error: function (data) {
                $("#load-icon").text("No faces detected for this video: Can't generate actor.")
            }
        })
    }
    function remfav(button) {
        const Http = new XMLHttpRequest();
        const url = "{% url 'viewer:rem_favorites' video.id %}"
        Http.open("GET", url);
        Http.send();
        button.setAttribute("onClick", "addfav(this)");
        button.setAttribute("id", "add-fav");
        $(button).children()[0].setAttribute("class", "far fa-heart");
    }
    function remvid(button) {
        $.ajax({
            url: "{% url 'viewer:rem_video' %}",
            method: "POST",
            data: {
                video_id: "{{video.id}}"
            }, success: function (data) {
                window.location = "/";
            }
        })
        console.log("Send post request!")
    }
    function remVideoLabel(button) {
        $(button).parent().hide();
        $.ajax({
            url: "{% url 'viewer:label-video-delete' %}",
            method: "POST",
            data: {
                label_id: $(button).attr("label-id"),
                video_id: "{{video.id}}"
            }
        })
    }
    $(document).ready(function () {
        rating_val = parseFloat("{{video.rating}}")
        if (rating_val > 0) {
            if (rating_val % 1 != 0) {
                final = "half";
                rating_val = parseInt(rating_val);
            } else {
                final = "";
            }
            rat_selector = "#star" + rating_val + final;
            $(rat_selector).prop("checked", true);
        }
        $(".rating input").on("click", function () {
            rating = $(this).val();
            console.log(rating)
            console.log(this)
            $.ajax({
                url: "{% url 'viewer:rate-video' %}",
                method: "POST",
                data: {
                    rating: rating,
                    video_id: "{{video.id}}"
                }
            })
        });
        document.getElementById("video-info-age").onchange = function () {
            age = $(this).val();
            console.log(age)
            $.ajax({
                url: "{% url 'viewer:change-age' %}",
                method: "POST",
                data: {
                    age: age,
                    video_id: "{{video.id}}"
                }
            })
        };
        document.getElementById("label-choice").onchange = function () {
            var chosen_label = $(this).val();
            $.ajax({
                url: "{% url 'viewer:label-video-add' %}",
                method: 'POST',
                data: {
                    video_id: "{{video.id}}",
                    label_id: chosen_label
                },
                success: function (data) {
                    new_label = "<div class=\"video-label col-lg-2\"><a href=\"/label/" + data["label_id"] + "/\">" + data["label"] + "</a><a onclick=\"remVideoLabel(this)\" class=\"delete-icon\" label-id=\"{{v_label.id}}\"><i class=\"fas fa-trash-alt\"></i></a></div>"
                    $(".video-labels").append(new_label);
                },
                error: function (xhr, errmsg, err) {
                    console.log(errmsg)
                    console.log(err)
                }
            })

        }
    });

</script>
{% endblock %}